package com.coindesk.controller;

import com.coindesk.model.Customer;
import com.coindesk.services.impl.CustomerService;

import io.swagger.annotations.*;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.util.UriComponentsBuilder;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

@RestController // This means that this class is a Controller
@RequestMapping(path="/customer") // This means URL's start with /customer (after Application path)
@Api(value = "Home Controller", description = "Operations pertaining to Customers.")
public class CustomerController {
    //@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomerService customerService;
    public CustomerController(CustomerService _service){
        customerService = _service;
    }

    @ApiOperation(value = "Returns all list of users.", response = List.class)
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successfully retrieved list"),
            @ApiResponse(code = 401, message = "You are not authorized to view the resource"),
            @ApiResponse(code = 403, message = "Accessing the resource you were trying to reach is forbidden"),
            @ApiResponse(code = 404, message = "The resource you were trying to reach is not found")
    }
    )
    @GetMapping(path="/")
    public @ResponseBody Iterable<Customer> getAllUsers() {
        // This returns a JSON or XML with the users
        return customerService.search();
    }

    @ApiOperation(value = "Stores the user.", response = Customer.class)
    @PostMapping(path="/") // Map ONLY POST Requests
    public @ResponseBody
    ResponseEntity<Customer> addNewUser (@ApiParam(value = "User details", required = true) @RequestBody Customer newCustomer,
                                         UriComponentsBuilder builder) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        customerService.insert(newCustomer);

        HttpHeaders headers = new HttpHeaders();
        headers.setLocation(builder.path("/{id}")
                .buildAndExpand(newCustomer.getId()).toUri());
        return new ResponseEntity<Customer>(HttpStatus.CREATED);
    }

    @ApiOperation(value = "Returns User if ID is found.", response = Customer.class)
    @GetMapping(path="/{id}")
    public @ResponseBody Customer findUser(@PathVariable("id") long id){
        return (Customer) customerService.searchID(id);
    }

    @ApiOperation(value = "Updates the user based Id.")
    @PutMapping(path="/{id}")
    public @ResponseBody ResponseEntity<String> updateUser(@PathVariable long id,
                                                           @RequestBody Customer updateCustomer){
        String value = customerService.change(id, updateCustomer);
        return new ResponseEntity<String>(value, HttpStatus.MULTI_STATUS);
    }

    /*
    *
    * @GetMapping("/valid-name/{name}")
        public void createUsername(@PathVariable("name") @NotBlank @Size(max = 10) String username) {
            // ...
        }
    *  */

    @ApiOperation(value = "Deletes the user based on given Id.")
    @DeleteMapping(path = "/{id}")
    public @ResponseBody ResponseEntity<String> deleteCustomer(@PathVariable long id,
                                                               @RequestBody Customer deleteCustomer){
        String value = customerService.delete(id, deleteCustomer);
        return new ResponseEntity<String>(value, HttpStatus.MULTI_STATUS);
    }

}