package com.coindesk.controller;

import com.coindesk.model.Customer;
import com.coindesk.repository.CustomerRepository;
import com.coindesk.service.CustomersService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    //@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomersService serviceNow;
    public MainController(CustomerRepository _service){
        serviceNow = new CustomersService(_service);
    }

    @GetMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String firstName
            , @RequestParam String lastName) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Customer newCustomer = new Customer(firstName, lastName);

        serviceNow.insert(newCustomer);
        return "Saved";
    }

    @GetMapping(path="/find/{id}")
    public @ResponseBody Customer findUser(@PathVariable long id){
        return (Customer) serviceNow.searchID(id);
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Customer> getAllUsers() {
        // This returns a JSON or XML with the users
        return serviceNow.search();
    }
}